- aws/elb.go
- aws/metadata.go
- docs/user/backends.md
- eureka/eureka.go
- modules.go
This branch adds some hudl required functionality:
1. Get AWS metadata to populate datacenter info correctly if the `SERVICE_eureka_datacenterinfo_auto_populate` flag is set to true.
2. Change the `instanceID` in the datacenter info to be a unique ID (comprised of IP_Port) which matches `hostName`.  This is a required workaround, because otherwise eureka does not correctly identify each container uniquely.  The actual instanceID has been moved to an `aws_instanceID` metadata item.
3. Add a new metadata item for `containerID`
4. Add an `is_container` flag to the metadata for each container
5. Add a `SERVICE_eureka_register_aws_public_ip` boolean flag, to register the AWS public IP instead of the private IP of the container host if required.
6. Add the ability to register an ELBv2 …
> Add ELBv2 support, public IP registration, AWS metadata population

- aws/elb.go
- aws/metadata.go
- aws/metadata_test.go
- bridge/util.go
- eureka/eureka.go
- Add unit tests for metadata, and some refactoring to allow testability
- Some small metadata fixes discovered during testing (such as container name being missing from bridge.go)
- Make metadata naming consistent - use `-` instead of `_`.
> Add metadata unit tests and some fixes

- aws/elb.go
- aws/elb_test.go
- aws/metadata.go
- aws/metadata_test.go
- eureka/eureka.go
- interfaces/interfaces.go
This PR does a couple of things:
1. Add unit tests for ELBs.
2. Change/improve metadata unit tests
3. Add some basic caching, so AWS metadata is cached at startup (specific to host)
4. Add a basic cache for ELBv2, so the AWS API will only be used when adding new containers, and not for heartbeats.
> Add ELB Unit Tests, Improve Performance

- aws/elb.go
- aws/metadata.go
1. Fix ELBv2 port retrieval, by instead returning the listener port on the load balancer (was returning the target group port, which is irrelevant)
2. Also, fix missing paging over target groups by creating two new helper functions.  Previously, only the first 400 target groups were being retrieved.  Unfortunately there doesn't seem to be a more efficient way to do this than looping through all target groups, though suggestions are welcome - API docs are here: https://docs.aws.amazon.com/sdk-for-go/api/service/elbv2/#DescribeTargetGroupsInput
> Fix ELBv2 port, and target group retrieval

- aws/elb.go
- aws/elb_test.go
- aws/metadata_test.go
- eureka/eureka.go
ELBv2 was not being correctly deregistered as intended.  This fixes that problem, and adds a small fix to prevent a possible panic if a load balancer is not found during registration.
> Fix ELB deregistration

- aws/elb.go
- aws/elb_test.go
- aws/metadata_test.go
- bridge/bridge.go
- eureka/eureka.go
- registrator.go
This PR does this:
- Remove separate ELBv2 registrations, instead register the ELB hostname as the eureka ipAddr and vipAddress
- Add the metadata about the ELBv2 as previously
- HostName remains a unique identifier for the running container so is <container host ip>_<host port>
- Introduce a delay in registration when using ELBs to allow for the time taken to add the container to the target group.
> Remove Separate ELB Registration

- Dockerfile
- Dockerfile.race
- aws/elb.go
- aws/elb_test.go
- bridge/bridge.go
- docs/user/backends.md
This PR tries to work around some of the sleepiness problems with ELB registration.
This PR adds two new options for container labels/variables:
- `SERVICE_EUREKA_ELBV2_HOSTNAME` 
- `SERVICE_EUREKA_ELBV2_PORT`
These can be set to explicitly specify the load balancer hostname and port at runtime to provide an alternative to a dynamic lookup, which is slow (because it has to sleep for a little while while the container joins the target group).
The PR also renames the older flag to  `SERVICE_EUREKA_LOOKUP_ELBV2_ENDPOINT` from `USE`.  This just makes it more obvious that the flag will be used for automatic lookup.  If you specify the older flag _and_ the explicit variables, then the explicits will be used in preference.
> Add explicit ELBv2 options

- Dockerfile
- Dockerfile.dev
Fix the missing ca-certificates resulting from the change to alpine 3.5.  These are required for any HTTPS communication to work correctly.
> Fix missing ca-certificates in alpine 3.5

- Makefile
- bridge/bridge.go
- bridge/types.go
- docs/user/run.md
- registrator.go
Fixes issue https://github.com/hudl/registrator/issues/15
- Add a new command line option to registrator: `-require-label`
- Change Makefile to make testing easier.  `make dev` still registers local eureka container that it starts for convenience when testing.
- Update documentation accordingly
Example:
If you specify `-require-label` when starting registrator,  it will check for a label called SERVICE_REGISTER on every new container.  If this is not present, the container will not be registered.  
*Note:* This can be set to ANY string, e.g true, yes, 1, would all work. Setting the label to a "falsey" value will NOT do the opposite.  
If you instead wish to include all containers and blacklist a few, you should leave off this flag, and set the SERVICE_IGNORE label on those containers you …
> Add startup option require-label to only register particular containers

- aws/elb.go
- eureka/eureka.go
This PR reworks things so that HostName is not used as an identifier in most circumstances.
1. AWS instanceID is updated to <IP>_<Port> when using the AWS datacentre type (default).  This is the case whether running locally or on AWS.
2. When running on AWS, you need to set the `eureka_datacenterinfo_auto_populate` flag to get the actual data centre information.
3. Eureka `HostName` will get set to the AWS _private_ hostname, if that is available.  
4. Eureka `HostName` will only fallback to an IP address, if auto populate is turned off, and no name is provided with the `eureka_datacenterinfo_localhostname` option.
5. If you set `eureka_lookup_elbv2_endpoint` or manually set `eureka_elbv2_hostname` and `eureka_elbv2_port` then these will be registered as appropriate.  However, when using …
> Make HostName a HostName again.

- Dockerfile
- Dockerfile.dev
- Makefile
- aws/elb.go
- aws/elb_test.go
- bridge/bridge.go
- docs/user/backends.md
- registrator.go
- run-registrator.sh
- service-config/environment-sidecartest.yaml
- service-config/environment-thormaster.yaml
- service-config/service.yaml
Add new checks to make sure there is a healthy container when registering a new ELB
- If there are no healthy containers when initially registered, register ELB as status STARTING.
- On each subsequent heartbeat, check the target group again for healthy containers, reregister with status UP if one or more is available.
- Additionally tee the log file to /logs/registrator-$HOSTNAME.log inside the container.  In practice this hostname will be the container ID, or a short version of it.  This should then allow logs to flow into sumo given previous changes already made for the log volume. 
*Optimisations:*
*Configuration*
Testing
> Add check for healthy containers before registering a new ELB as up.

- service-config/environment-prod.yaml
- service-config/environment-stage.yaml
- service-config/environment-testsidecar.yaml
Add the stage and prod environment files.
NOTE: Prod is currently set to the thor eureka server, just for safety.  It can be changed manually by creating a new task definition version at go-live time.
> Add stage and prod envrionments

- Dockerfile.race
- Makefile
- aws/elb.go
- aws/elb_test.go
- bridge/bridge.go
- docs/user/backends.md
- service-config/environment-prod.yaml
- service-config/environment-stage.yaml
- service-config/environment-testsidecar.yaml
- service-config/environment-thor.yaml
- service-config/service.yaml
Improve the efficiency of ELBv2 lookups by using some ECS labels to identify the cluster and service.
- Add all labels starting `com.amazonaws.ecs` to the service attributes.
- Check for `com.amazonaws.ecs.cluster` and `com.amazonaws.ecs.task-arn`.  If present, these can be used to lookup the service name.  This  and the cluster name are then used to retrieve the target group and load balancer details, rather than looping through all target groups.
- If these labels aren't present, then previous behaviour is preserved.
- A fix to try to help behaviour around ALB dropouts - there may have been a data race between resync and refresh (heartbeat)
Tests:
> Reduce chances of throttling of AWS API, making ELBv2 lookups more efficient

- service-config/service.yaml
placement_constraints was moved, but deployment_options wasn't.
This moves deployment_options to the correct spot
> move deployment options to correct spot.

- Makefile
- aws/elb.go
- aws/elb_test.go
- eureka/eureka.go
- registrator.go
This PR fixes 3 issues.
1) Registrator wasn't reregistering if a instance drops out of eureka.  This was causing an issue with local development when a user would wake their computer from sleep.  We now re-register if we receive a 404 from a heartbeat.
2) Registrator will cause a panic if no ELB data is returned from cache, which can happen if the ELB is deleted.  This adds a fix for that and a unit test.
3) Adds IP address validation
> Add Re-Register, fix ELB cache panic, add IP validation

- Makefile
- eureka/eureka.go
checkBooleanFlag() was being used like it should return the value of the boolean.. but the function was written to check whether it is a boolean or not. If you had the value false, it would still return true.
This caused SERVICE_eureka_datacenterinfo_auto_populate: 'false' being set to register instances with a blank hostname, resulting in instance ids being  `_{port}`
This fixes that issue.
> return value for checkBooleanFlag, rather than if exists or not

- bridge/bridge.go
- docker-compose.yml
- registrator.go
- service-config/environment-thor.yaml
- service-config/service.yaml
As per ticket MARVEL-2100 we have added additional logging, stopped ignoring some errors and added a global recover for any panics that somehow went under the radar.
- `docker-compose.yml` file for easier debugging on Windows
- `recover()` deferred function added
- Additional logging
- Some ignored errors reinstated
Is it worth us upgrading to the official docker go SDK instead of third party? It may alleviate our issues.
> WIP - MARVEL-2100 - Add logging to `registrator`

- bridge/bridge.go
- bridge/types.go
- bridge/util.go
This PR enables an additional config option via labels - `SERVICE_USE_EXPOSED_PORTS`. When this is provided it would utilise the exposed port on the container for registration as opposed to the Host port.
> MARVEL-2583 - Use Exposed Ports

- bridge/util.go
- docker-compose.yml
- registrator.go
This PR adds retry logic (basic), introduce a HttpClient and a timeout, and a new config value, `ip-lookup-retries` which defaults to `1`. 
Scenario: _Load up registrator with internet and see connection made. Load up without and see failure. On 3 failures exit. On 2 failures and reconnect reset and succeed._
=============
> MARVEL-2680 - Added retry and timeouts to the VPN IP Check

- bridge/bridge.go
- eureka/eureka.go
- registrator.go
Ignoring the branch name, this is actually nothing to do with the metadata IP's and that is a red herring. The actual issue has probably been there since IP lookups from a source were added, and it has been plaguing people in various ways, we just suspect people have been dealing with it, nuking docker, containers etc.
In the event of a docker container being registered, it would take the container ID, look it up and grab it's IP and register it with that.
If there was then a network change, it would re-register the service with the correct IP, however if there wasn't a network change you would end up with a service registered in Eureka with this phony IP indefinitely, short of restarting everything and re/connecting to VPN etc. 
This has been resolved by now providing the IP with any …
> NOTICK - Resolve issue around `docker` events and resyncing ip's

- build-image.sh
This PR is a change for the build script, to publish master releases to the `latest` tag in ECR again.  This will allow marvel services to easily pull to the latest version and allow fixes to be rolled out more quickly.
> Marvel-2837 Publish latest tag for master

- bridge/types.go
- bridge/util.go
- registrator.go
Previously Registrator would stop when it's unable to update it's IP address.  This change will make it so it will continue. I've added a `-exit-on-ip-lookup-failure` flag to switch back to the previous behavior.
I made it `exit-on-ip-lookup-failure` rather than `continue-on-ip-lookup-failure` to maintain backwards compatibility since we're using `registrator:latest` and we have no control over when registrator will update.
> MARVEL - Add Flag to not exit on inability to get IP address.

- run-registrator.sh
- service-config/environment-stage.yaml
- service-config/environment-thor.yaml
- service-config/service.yaml
Registrator logged to a file so we could have our Sumo Logic container read the log files in.  This switches to logging only to console and using the log driver instead.
> MARVEL-2642 - Log to console
